version: 2.1

jobs:
  build:
    docker:
      - image: circleci/node:20
    steps:
      - checkout
      - run: npm install
      - run: npm test

workflows:
  version: 2
  build-deploy:
    jobs:
      - build